# Generated by Django 3.2.9 on 2021-12-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
